export const servicesData =  {
    categories: ['Residential', 'Commercial'],
    services: [
        { id: 1, image: '/img/Services/service-1.jpg', title: 'Trash', category: 'Residential', description: 'Trash pick up twice a week', cost: 80 },
        { id: 2, image: '/img/Services/service-2.jpg', title: 'Recycling', category: 'Residential', description: 'Recycling pick up once a week', cost: 10 },
        { id: 3, image: '/img/Services/service-3.jpg', title: 'Organics', category: 'Residential', description: 'Organics pick up two a month', cost: 15 },
        { id: 4, image: '/img/Services/service-4.jpg', title: 'Energy Investment', category: 'Commercial', description: 'A portion of your energy bill is covered through the incinerator program.', cost: 8000 },
        { id: 5, image: '/img/Services/service-5.jpg', title: 'Indoor Fitting', category: 'Commercial', description: 'We deliver cans and pick up twice per week for your entire building.', cost: 7500 },
        { id: 6, image: '/img/Services/service-6.jpg', title: 'Dumpsters', category: 'Commercial', description: 'A variety of dumpster sizes available', cost: 9000 },
        { id: 7, image: '/img/Services/service-7.jpg', title: 'Projects', category: 'Commercial', description: 'Construction and long term projects are covered on a monthly flat rate.', cost: 8000 },
        // { id: 8, image: '/img/Services/service-4.jpg', title: 'Roll-Off', category: 'Residential', description: 'Home remodeling, large projects, all covered on a weekly flat rate.', cost: 9000 },
        { id: 9, image: '/img/Services/service-9.jpg', title: 'Couples Day', category: 'Water', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/img/Services/service-10.jpg', title: 'Pedicure', category: 'Ammenities', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/img/Services/service-11.jpg', title: 'Girls Day', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/img/Services/service-12.jpg', title: 'Group Gathering', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/img/Services/service-13.jpg', title: 'Cold and Hot Treament', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/img/Services/service-14.jpg', title: 'Service 14', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/img/Services/service-15.jpg', title: 'Full Body Scrub', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/img/Services/service-16.jpg', title: 'Deep tissue', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/img/Services/service-17.jpg', title: 'Hot Stone Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/img/Services/service-18.jpg', title: 'Hot, Cold and In Between', category: 'Water', description: 'A description of our service...', cost: 3500 },
        { id: 19, image: '/img/Services/service-19.jpg', title: 'Me Time', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 20, image: '/img/Services/service-20.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}